# Generated by Django 4.2.11 on 2025-02-28 21:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinalPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("arrival_datetime", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="StartPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("departure_datetime", models.DateTimeField()),
                ("travel_method_to_next", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="TravelPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("plan_name", models.CharField(max_length=255)),
                (
                    "final_point",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapi.finalpoint",
                    ),
                ),
                (
                    "start_point",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapi.startpoint",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ViaPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("index", models.IntegerField()),
                ("location", models.CharField(max_length=255)),
                ("arrival_datetime", models.DateTimeField()),
                ("priority", models.CharField(max_length=50)),
                ("departure_datetime", models.DateTimeField()),
                ("travel_method_to_next", models.CharField(max_length=50)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="via_points",
                        to="myapi.travelplan",
                    ),
                ),
            ],
        ),
    ]
