services:
  - type: web
    name: tabinosuke-api
    env: docker
    plan: starter
    region: singapore
    buildCommand: pip install -r requirements.txt
    dockerCommand: python manage.py migrate && python manage.py runserver 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tabinosuke-db
          property: connectionString
      - key: PORT
        value: "8000"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: google_api_key
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
    healthCheckPath: /api/health/
    autoDeploy: true

databases:
  - name: tabinosuke-db
    plan: starter
    ipAllowList: []  # 必要に応じてIPリストを追加する
